<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"><channel><title>工作遇到的问题 - Category - ImportMengjie's Blog</title><link>https://importmengjie.github.io/categories/%E5%B7%A5%E4%BD%9C%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98/</link><description>工作遇到的问题 - Category - ImportMengjie's Blog</description><generator>Hugo -- gohugo.io</generator><language>zh-CN</language><managingEditor>limengjie@hotmail.com (mengjie)</managingEditor><webMaster>limengjie@hotmail.com (mengjie)</webMaster><lastBuildDate>Thu, 21 Sep 2023 14:11:24 +0800</lastBuildDate><atom:link href="https://importmengjie.github.io/categories/%E5%B7%A5%E4%BD%9C%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98/" rel="self" type="application/rss+xml"/><item><title>记一次虚函数二进制兼容问题导致的coredump</title><link>https://importmengjie.github.io/posts/vtable-coredump/</link><pubDate>Thu, 21 Sep 2023 14:11:24 +0800</pubDate><author>mengjie</author><guid>https://importmengjie.github.io/posts/vtable-coredump/</guid><description>问题排查 问题表面 首先找到程序挂掉前打印出如下： terminate called after throwing an instance of &amp;#39;std::system_error&amp;#39; what(): Resource deadlock avoided Aborted google了下，大概率是因为以下两个原因: 线程自己join自己 =&amp;gt; 悖</description></item></channel></rss>